spring.application.name=postboard

# Connessione a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postboard_db
spring.datasource.username=postgres
spring.datasource.password=160304

# Hibernate / JPA
# "update" crea o aggiorna le tabelle in automatico basandosi sul codice Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect